---
- name: Install some required apt packages for the Sury repo
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - apt-transport-https
    - ca-certificates
    - lsb-release

- name: Add the Sury apt key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg

- name: Configure the Sury repo
  apt_repository:
    filename: sury
    repo: 'deb https://packages.sury.org/php/ jessie main'
